# Generated by Django 2.0.3 on 2021-03-13 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=512)),
                ('author', models.CharField(max_length=128)),
                ('publish_date', models.CharField(max_length=32)),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ratings_count', models.IntegerField()),
                ('page_count', models.IntegerField()),
                ('description', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(default='default.png', upload_to='usr')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
