# Generated by Django 2.0.3 on 2021-03-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=512)),
                ('author', models.CharField(max_length=128)),
                ('publish_date', models.CharField(max_length=32)),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ratings_count', models.IntegerField()),
                ('page_count', models.IntegerField()),
                ('description', models.CharField(max_length=4096)),
            ],
        ),
    ]
