# Generated by Django 2.0.3 on 2021-03-08 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='book',
            new_name='isbn',
        ),
    ]
