# Generated by Django 2.0.3 on 2021-03-08 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20210308_0505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='isbn',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
