# Generated by Django 2.0.3 on 2021-03-08 06:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20210308_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 6, 13, 19, 694513, tzinfo=utc)),
        ),
    ]
