# Generated by Django 2.0.3 on 2021-03-13 10:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0018_auto_20210313_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 10, 11, 0, 7554, tzinfo=utc)),
        ),
    ]
